export enum ScopeTypeEnum {
  Cabinetry = 1,
  Countertops = 2,
  ResidentialInteriorPrehungDoors = 3,
  CommercialDoors = 4,
  BroadloomCarpet = 5,
  LVP = 6,
  LVT = 7,
  Tile = 8,
  CommercialDoorHardware = 9,
  Baseboards = 10,
  Epoxy = 11,
  PolishedConcrete = 12,
  SealedConcrete = 13,
  Casings = 14,
  CarpetTile = 15,
  Mirrors = 16,
  ResidentialExteriorPrehungDoors = 17,
  Shelving = 18,
  ResilientAthleticFlooring = 19,
  RubberBase = 20,
  RoughInDoorFrames = 21,
  PresetCommercialDoors = 22,
  InteriorDoorHardware = 23,
}
