export interface TaskDetails {
  taskId: number;
  unitId: number;
  parentTaskId: number;
  parentTaskTypeId: number;
  parentTaskTypeName: string;
  parentStatusId: number;
  parentStatusName: string;
  taskTypeId: number;
  taskTypeName: string;
  phaseId: number;
  phaseName: string;
  statusId: number;
  statusName: string;
  imageAcknowledgmentChecked: boolean;
  imageAcknowledgmentText: string;
  assignedWorkerId: number;
  assignedWorkerName: string;
  scheduledDate: Date;
  scheduledById: number;
  submittedAt: Date;
  submittedBy: number;
  submissionNotes: string;
  reviewedAt: Date;
  reviewedBy: number;
  reviewNotes: string;
  taskDetails: string;
  createdAt: Date;
  createdBy: number;
  updatedAt: Date;
  updatedBy: number;
  deletedAt: Date | null;
  deletedBy: number | null;
  images: any;
  proofImages: any;
  reviewImages: any;
  rootMainTaskId: number | null;
  rootTaskTypeId: number | null;
  secondaryWorkerName: string | null;
  clearInspection: any;
  subtasks: any;
}
