export interface UnitTask {
  taskId: number;
  unitId: number;
  parentTaskId: number | string;
  parentTaskTypeId: number;
  parentTaskTypeName: string;
  parentStatusId: number;
  parentStatusName: string;
  taskTypeId: number;
  taskTypeName: string;
  scopeTypeId: number;
  scopeTypeName: string;
  phaseId: number;
  phaseName: string;
  statusId: number;
  statusName: string;
  imageAcknowledgmentChecked: boolean;
  imageAcknowledgmentText: string;
  assignedWorkerId: number;
  assignedWorkerName: string;
  workerUserId: number;
  scheduledDate: Date | string;
  scheduledById: number;
  submittedAt: Date | string;
  submittedBy: number;
  submissionNotes: string;
  reviewedAt: Date | string;
  reviewedBy: number;
  reviewNotes: string;
  taskDetails: string;
  createdAt: Date | string;
  createdBy: number;
  updatedAt: Date | string;
  updatedBy: number;
  deletedAt: Date | string;
  deletedBy: number;
  images: any;
  clearInspection: any;
  unitByScopeId: number;
  secondaryWorkerId?: number;
  secondaryWorkerName?: string;
}
